name: 'Terraform Destroy'

on:
  push:
    branches:
    - master
    paths:
    - lab3-var-module/app2/**
  pull_request:

permissions:
  contents: read

jobs:
  terraform-init:
    name: 'Terraform'
    runs-on: gabriel-runner
    env: 
      ENVIRONMENT: lab

    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init
      working-directory: lab3-var-module/app2/

    - name: Terraform workspace new - LAB
      if: github.ref == 'refs/heads/master'
      run: terraform workspace new lab
      working-directory: lab3-var-module/app2/
      continue-on-error: true

    - name: Terraform workspace select - LAB
      if: github.ref == 'refs/heads/master'
      run: terraform workspace select lab
      working-directory: lab3-var-module/app2/

    - name: Terraform Apply - LAB
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: terraform destroy -var-file=app2.tfvars --auto-approve -input=false
      working-directory: lab3-var-module/app2/